"""швл

Revision ID: d5b6ada418fe
Revises: dc627d7b87de
Create Date: 2025-12-16 21:56:49.062123

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd5b6ada418fe'
down_revision: Union[str, Sequence[str], None] = 'dc627d7b87de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
