"""add created_at and updated_at fields to cart table

Revision ID: f9328536d7a7
Revises: cad5e101dd0b
Create Date: 2025-12-18 00:50:12.416691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9328536d7a7'
down_revision: Union[str, Sequence[str], None] = 'cad5e101dd0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cart', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'updated_at')
    op.drop_column('cart', 'created_at')
    # ### end Alembic commands ###
